version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      RAILS_ENV:
    entrypoint: wait-for-it.sh db:5432 -t 30 -s --

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
